# Generated by Django 4.1.1 on 2022-10-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_data_migration_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ('-create_date',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ('course', 'num'), 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-create_date',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ('name', 'surname'), 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
